# Generated by Django 4.2.10 on 2024-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
