# Generated by Django 4.2.10 on 2024-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
