# Generated by Django 4.1.5 on 2024-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_response_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_response',
            field=models.IntegerField(default=0),
        ),
    ]
