# Generated by Django 4.1.5 on 2024-03-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users_total_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=10)),
                ('linkedin_profile', models.CharField(max_length=40)),
                ('experience', models.IntegerField(default=0, max_length=2)),
                ('designation', models.TextField(max_length=20)),
                ('introduction', models.CharField(max_length=70)),
                ('domains', models.TextField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
