# Generated by Django 4.1.5 on 2024-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mentor_experience_alter_mentor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='introduction',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin_profile',
            field=models.CharField(max_length=50),
        ),
    ]
