# Generated by Django 4.1.5 on 2024-03-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_mentor_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
