# Generated by Django 4.1.5 on 2024-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mentor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='introduction',
            field=models.CharField(max_length=400),
        ),
    ]
