# Generated by Django 4.1.5 on 2024-03-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_mentor_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
