# Generated by Django 4.1.5 on 2024-03-05 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_users_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='designation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='domains',
            field=models.CharField(max_length=12),
        ),
    ]
