# Generated by Django 4.1.5 on 2024-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mentor_created_at_alter_mentor_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='points',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_query',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_response',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
