# Generated by Django 4.1.5 on 2024-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_users_points_alter_users_total_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='users',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='total_response',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
