# Generated by Django 4.1.5 on 2024-03-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_query_desc_alter_response_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='domains',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
