# Generated by Django 4.1.5 on 2024-03-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_mentor_domains_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='introduction',
            field=models.TextField(max_length=400),
        ),
    ]
