# Generated by Django 4.1.5 on 2024-03-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_mentor_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_mentor',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
